### ISSUE TITLE
Log Spam

### ISSUE THREAD

**Issue by reddvilzz** [Darkhax-Minecraft/WAWLA#39]
Hi, I got this log spam

> [00:15:55] [NEI Item Filtering/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.event.entity.player.ItemTooltipEvent@6af0abf4:
java.lang.NullPointerException
	at com.darkona.adventurebackpack.block.BlockAdventureBackpack.getAssociatedTileColorName(BlockAdventureBackpack.java:109) ~[BlockAdventureBackpack.class:?]
	at com.darkona.adventurebackpack.block.BlockAdventureBackpack.getEnchantPowerBonus(BlockAdventureBackpack.java:126) ~[BlockAdventureBackpack.class:?]
	at net.darkhax.wawla.addons.generic.AddonGenericTooltips.onTooltip(AddonGenericTooltips.java:65) ~[AddonGenericTooltips.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1011_AddonGenericTooltips_onTooltip_ItemTooltipEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:169) [ForgeEventFactory.class:?]
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:626) [add.class:?]
	at codechicken.nei.guihook.GuiContainerManager.itemDisplayNameMultiline(GuiContainerManager.java:119) [GuiContainerManager.class:?]
	at codechicken.nei.guihook.GuiContainerManager.concatenatedDisplayName(GuiContainerManager.java:162) [GuiContainerManager.class:?]
	at codechicken.nei.api.ItemInfo.getSearchName(ItemInfo.java:529) [ItemInfo.class:?]
	at codechicken.nei.ItemList$PatternItemFilter.matches(ItemList.java:65) [ItemList$PatternItemFilter.class:?]
	at codechicken.nei.ItemList$AnyMultiItemFilter.matches(ItemList.java:110) [ItemList$AnyMultiItemFilter.class:?]
	at codechicken.nei.ItemList$AllMultiItemFilter.matches(ItemList.java:85) [ItemList$AllMultiItemFilter.class:?]
	at codechicken.nei.ItemList$2.execute(ItemList.java:239) [ItemList$2.class:?]
	at codechicken.nei.RestartableTask$1.run(RestartableTask.java:24) [RestartableTask$1.class:?]
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: Index: 25 Listeners:
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 0: HIGHEST
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 1: ASM: vazkii.botania.client.core.handler.TooltipHandler@cf6a4a1 onTooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 2: ASM: ganymedes01.ganysnether.core.handlers.TooltipEvent@92358b3 getTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 3: ASM: tombenpotter.sanguimancy.util.EventHandler@2060495c onSanguimancyItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 4: ASM: witchinggadgets.client.ClientEventHandler@5bca6e9a getTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 5: ASM: iguanaman.iguanatweakstconstruct.tweaks.handlers.StoneToolHandler@7a10534a onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 6: HIGH
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 7: ASM: iguanaman.iguanatweakstconstruct.leveling.handlers.LevelingToolTipHandler@bffc577 onItemToolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 8: NORMAL
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 9: ASM: buildcraft.core.list.ListTooltipHandler@5aca021c itemTooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 10: ASM: com.darkona.adventurebackpack.handlers.ClientEventHandler@40047e44 toolTips(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 11: ASM: net.bdew.lib.tooltip.TooltipHandler$@2786c884 handleTooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 12: ASM: thaumcraft.common.lib.events.EventHandlerRunic@73537df2 tooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 13: ASM: com.rwtema.extrautils.modintegration.TConEvents@53c6be50 unstableTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 14: ASM: com.brandon3055.draconicevolution.common.handler.MinecraftForgeEventHandler@455bb840 itemTooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 15: ASM: crazypants.enderio.machine.painter.BlockPaintedGlowstone$PainterTemplate@16a9a779 onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 16: ASM: com.pam.harvestcraft.PamTooltipEventHandler@508e7b5e onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 17: ASM: minetweaker.mc1710.ForgeEventHandler@129961fa onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 18: ASM: ftb.lib.mod.client.FTBLibClientEventHandler@449b00e4 onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 19: ASM: mcp.mobius.betterbarrels.bspace.BBEventHandler@767a7d7b onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 20: ASM: mariculture.core.gui.GuiItemToolTip@4babe2ba addToolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 21: ASM: mariculture.fishery.BaitListingsHandler@612748c addToolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 22: ASM: tonius.neiintegration.mods.mcforge.MCForgeTooltipHandler@1ba84740 onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 23: ASM: openblocks.enchantments.flimflams.LoreFlimFlam$DisplayHandler@3ecae0e9 onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 24: ASM: openperipheral.addons.glasses.client.TerminalManagerClient$ForgeBusListener@3562e5d2 onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 25: ASM: net.darkhax.wawla.addons.generic.AddonGenericTooltips@22d2408a onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 26: ASM: com.InfinityRaider.AgriCraft.handler.ItemToolTipHandler@1867b1fe addTrowelTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 27: ASM: com.InfinityRaider.AgriCraft.handler.ItemToolTipHandler@1867b1fe addClipperTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 28: ASM: com.InfinityRaider.AgriCraft.handler.ItemToolTipHandler@1867b1fe addSeedStatsTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 29: ASM: fox.spiteful.forbidden.FMEventHandler@1dedc1f4 onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 30: ASM: com.pahimar.ee3.client.handler.ItemTooltipEventHandler@66e6fae5 handleItemTooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 31: ASM: com.rwtema.extrautils.EventHandlerClient@4de67be4 generatorTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 32: ASM: blusunrize.immersiveengineering.client.ClientEventHandler@682f9346 onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 33: ASM: buildcraft.builders.BuilderTooltipHandler@166d2030 itemTooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 34: ASM: INSTANCE onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 35: ASM: INSTANCE addTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 36: ASM: com.enderio.core.client.handlers.EnchantTooltipHandler@54faa245 handleTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 37: ASM: com.enderio.core.client.handlers.OreDictTooltipHandler@68608277 onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 38: ASM: crazypants.enderio.conduit.item.filter.ClearFilterRecipe@3828dc54 onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 39: ASM: crazypants.enderio.machine.ClearConfigRecipe@6d1009a4 onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 40: ASM: ganymedes01.ganysend.core.handlers.HandlerEvents@1637dacb tooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 41: ASM: invtweaks.forge.ClientProxy@1d3fa5c7 onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 42: ASM: modtweaker2.ClientEvents@948827b onDrawTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 43: ASM: squeek.spiceoflife.gui.TooltipHandler@41c779e9 onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 44: ASM: net.blay09.mods.tcinventoryscan.client.ClientProxy@31f868c1 onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 45: ASM: squeek.tictooltips.TooltipHandler@d30bcf8 onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 46: ASM: tconstruct.achievements.AchievementEvents@2d43f0cc tooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 47: ASM: iguanaman.iguanatweakstconstruct.harvestlevels.VanillaToolTipHandler@5a1b82ff onItemToolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 48: ASM: iguanaman.iguanatweakstconstruct.leveling.handlers.MobHeadTooltipHandler@20539356 onItemToolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 49: ASM: iguanaman.iguanatweakstconstruct.tweaks.handlers.VanillaToolNerfHandler@4c51abf onItemToolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 50: ASM: iguanaman.iguanatweakstconstruct.tweaks.handlers.VanillaHoeNerfHandler@6ba02847 onItemToolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 51: ASM: iguanaman.iguanatweakstconstruct.tweaks.handlers.VanillaSwordNerfHandler@6cb7c201 onItemToolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 52: ASM: iguanaman.iguanatweakstconstruct.restriction.PartRestrictionHandler@26f61c7b onItemToolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 53: ASM: xreliquary.event.CommonEventHandler@388a329b onEntityLiving(Lnet/minecraftforge/event/entity/living/LivingEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 54: LOW
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 55: ASM: iguanaman.iguanatweakstconstruct.replacing.PartToolTipHandler@5735b2ad onItemToolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 56: LOWEST
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 57: ASM: travellersgear.client.ClientProxy@595c0320 onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 58: ASM: org.blockartistry.mod.ThermalRecycling.events.ToolTipEventHandler@714ac5b3 onToolTipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:55] [NEI Item Filtering/ERROR] [FML/]: 59: ASM: iguanaman.hungeroverhaul.util.IguanaEventHook@59eeaf37 renderTooltips(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[00:15:58] [Client thread/INFO] [inventorytweaks/]: net.minecraft.client.gui.inventory.GuiInventory
[00:15:58] [Client thread/INFO] [inventorytweaks/]: net.minecraft.inventory.ContainerPlayer

It just keeps repeating over and over again every 20 - 30 seconds and I do not know how to fix it.
And I can't use pastebin to upload my log since it is 18mb big. Maybe I can give the full log in a different way?

**Comment by darkhax** [comment]
Thank you for reporting this. Which version are you using?

**Comment by reddvilzz** [comment]
Thank you for the response. I posted this on the AdventureBackpack mod as well since the log mention it, and here is the response from the developer

>     Quote from runescapejon >>



    hmm I'll get in contact with that dev to add support for adventurebackpack

    https://github.com/runescapejon/AdventureBackpack2/releases

and I am using the version Wawla-1.3.3-1.7.10 from the FTB Infinity Evolved

**Comment by darkhax** [comment]
Yes, I did get a very odd tweet from him asking me to add support from his mod. That is a very vague statement, and if the issue is my mod not having support for his mod, then he is doing something wrong. From looking into the 1.7.10 version of my code, I believe I have found the actual issue in Wawla's code though. It is currently very hard for me to update the 1.7.10 version of the mod, as my code and setup moved on to 1.8 and later to 1.9. I will look into creating another 1.7.10 build, and hopefully it will make its way into Infinity.

**Comment by reddvilzz** [comment]
Thank you. I'll wait for that I guess. May I know if this could be an issue if I just let it run until you can make a fix for it like performance issue because of the spamming? If so is there any temporary workaround until then?

**Comment by darkhax** [comment]
Well the issue should only be caused by hovering over that specific block from this mod in your inventory. So it's not a constant spam. Other then that, no other workarounds. Alternatively the mod author of that mod could (and probably should) add in some code to protect against mods probing his blocks for this specific info.

**Comment by reddvilzz** [comment]
If I check the log time it keep happening at a short amount of time. What I do is just clearing some area from jungle woods and leaves and while I look at it the log just keep repeating that. 

At first I thought it happened because I opened the inventory but looks like not. And I didn't even hovering anything from the mod since I haven't made the backpack just yet. 

Anyway should I tell the adventurebackpack developer to do what you are suggested? Maybe his part would be a bit easier since he still maintaining for 1.7.10

**Comment by darkhax** [comment]
Well the log shows the steps taken to get to this output, and they are being called by code that renders tooltips in NEI. As for passing my suggestion along, I will look into his mod code and write him a message later.

**Comment by reddvilzz** [comment]
Okay thank you. I guess I can close this issue or should I wait later till it really fixed?

**Comment by darkhax** [comment]
I will close it in a few minutes. Going to link to the release and such.

**Comment by darkhax** [comment]
This issue has been resolved in version [1.0.5.120](http://minecraft.curseforge.com/projects/wawla-what-are-we-looking-at/files/2298772) of Wawla. A special request has been made on the [AdventureBackpack2 GitHub](https://github.com/runescapejon/AdventureBackpack2/issues/4) that will help further resolve this issue.

**Comment by m0nkm0nk** [comment]
Im using 1.0.5.120 and still getting console spam. Not sure why it happens.
Console: https://pastebin.com/JMnAq63N 
Mods used: https://pastebin.com/kKYcPSjf

**Comment by darkhax** [comment]
@m0nkm0nk I need the full report, you've only given me the first bit. Also please create a new issue for your report.
